version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app-nest
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: db-nest
    restart: always
    ports:
      - 5432:5432
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=true
      - POSTGRES_DB=store
